name: CI (scheduled)

on:
  schedule:
    - cron: 0 14 * * 0 # Sunday 2PM UTC = Monday 12AM AEST

jobs:
  ci:
    name: ${ org_name }
    uses: ${ org }/repos/.github/workflows/shared-ci-${ ci_type }.yml@main
    secrets: inherit
    with:
      isScheduled: true
