on:
  workflow_call:
    inputs:
      isScheduled:
        description: Whether this CI workflow run is scheduled
        type: boolean
        required: false
        default: false

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: make link-dependencies

      - name: Make
        run: make ci

      - name: Publish coverage
        if: ${{ github.event.inputs.isScheduled != 'true' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
